package com.rsupport.webviewer.core.common;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.ToString;

@AllArgsConstructor
@ToString
@Getter
public enum ExceptionStatus {

    SUCCESS(1000, "success"),
    FAIL(2000, "fail"),
    DATA_SAVE_FAIL(902, ""),
    DATA_EXIST(2009, "data exists"),
    DATA_NOT_EXIST(2010, "data not exists"),
    EXISTS_SITE_ID(2011, "site id exists"),
    USER_NOT_REGISTERED(2012, "user not registered"),
    PASSWORD_LOGIN_FAIL(2013, "입력하신 이메일주소와 비밀번호가 일치하지 않습니다. 확인 후, 다시 시도해 주시기 바랍니다."),
    BADGE_NOT_REGISTERED(2014, "badge not registered"),
    USER_DUPLICATE_USERNAME(2016, "username duplicated"),
    NICKNAME_ALREADY_REGISTERED(2017, "nickname already exists"),
    NICKNAME_EARLY_CHANGED(2018, "nickname early changed"),
    BANNED_WORD(2019, "banned word"),
    NICKNAME_SIZE(2020, "nickname size must be between {0} and {1}"),
    NICKNAME_SPECIAL_CHARACTER(2021, "nickname invalid special characters"),
    TEAM_NAME_USED_BANNED_WORD(2036, "팀 이름에 금칙어가 포함되어 있습니다."),
    TEAM_CREATED_BEHIND_CONDITION_FOLLOWERCOUNT_AND_FOLLOWING_COUNT(2037, "팀 만들기는 팔로워 수가 {0}명 이상, 팔로잉 수가 {1}명 이상인 유저만 가능합니다"),
    TEAM_NAME_EXISTS(2038, "이미 등록된 팀 이름입니다."),
    SOCIAL_AUTH_USER(2022, "소셜 네트워크 계정으로 인증된 이메일입니다. 인증하신 소셜 네트워크 계정으로 로그인해주시기 바랍니다."),
    EXISTS_USER(2023, "이미 가입된 사용자 입니다."),
    PASSWORD_CONFIRM_INCORRECT(2024, "비밀번호가 일치하지 않습니다."),
    PASSWORD_RULE_NOT_MATCHES(2025, "알파벳 또는 숫자가 1글자 이상 포함되어야 합니다."),
    PASSWORD_MINIMUM_LENGTH(2026, "비밀번호는 최소 {0}글자 이어야 합니다."),
    NEED_EMAIL_AUTHENTICATION(2027, "이메일 인증이 필요합니다."),
    NOT_EXISTS_EMAIL(2028, "등록되지 않은 이메일 계정입니다."),
    NOT_MATCH_NICKNAME(2029, "이메일 계정과 닉네임이 일치하지 않습니다."),
    NOT_VALID_USER_CHANGE_PASSWORD(2030, "유효하지 않은 요청입니다. 메일을 다시 확인하여주세요."),
    CHANGE_PASSWORD_OVER_PERIOD(2031, "비밀번호 변경 기간이 만료되었습니다. 재 요청하시기 바랍니다."),
    NOT_TEAM_MANAGER(2033, "팀 정보 수정은 매니저만 가능합니다."),
    LOGO_IMAGE_USE_EXISTS(2034, "사용중이 이미지는 삭제 할 수 없습니다."),
    DO_NOT_DELETE_DEFAULT_IMAGE(2035, "기본이미지는 삭제 할 수 없습니다."),
    NOT_TEAM_MEMBER(2039, "팀의 멤버가 아닙니다."),
    NOT_CHAT_MEMBER(2400, "채팅멤버가 아닙니다."),
    TEAM_CHAT_UNDER_CONSTRUCTION(2410, "팀채팅이 점검중입니다."),
    USER_FAVORITE_LIMIT_OVER(2440, "즐겨찾기를 더이상 등록할 수 없습니다."),
    USER_BLOCK_USER(2500, "본 계정은 운영정책 위반으로 게임덕 이용이 영구적으로 제한되었습니다."),
    USER_UNSUBSCRIBED(2502, "탈퇴한 유저입니다. 데이터가 완전히 삭제되기 위해선 하루정도 시간이 소요 됩니다."),
    USER_MESSAGE_BLOCKED(2501, "{0}님은 현재 메시지 차단상태입니다."),
    BLOCKED(2503, "차단되었습니다."),
    UNBLOCKED(2504, "차단해제 되었습니다."),
    BLINDED(2505, "블라인드되었습니다."),
    UNBLINDED(2506, "블라인드 해제되었습니다."),
    AUTHED(2507, "인증 되었습니다."),
    AUTH_CANCELED(2508, "인증 해제되었습니다."),
    ALEADY_BLINDED(2509, "이미 블라인드되었습니다."),
    ALEADY_BLOCKED(2510, "이미 차단되었습니다."),
    USER_NOT_AUTHORIZED(2401, "사용자 권한이 없습니다."),
    NOT_EXISTS_FILE(2701, "존재하지 않는 파일"),
    VIDEO_FILE_TRANS_FAIL(2801, "비디오 파일 변환 실패"),
    VIDEO_FILE_TRANS_ING(2802, "비디오 파일 변환 중.."),
    CHANNEL_USE_POST_EXISTS(2803, "해당 채널을 이용한 포스트가 존재합니다."),
    EXISTS_CHANNEL(2805, "이미 게임이 존재합니다."),
    APP_UPDATE(2804, "신규 업데이트 내용이 존재합니다."),
    NOT_GAME(2806, "Game이 아닙니다."),
    CHANNEL_CATEGORY_USE_POST_EXISTS(2807, "해당 채널카테고리 이용한 포스트가 존재합니다."),
    CANNOT_DELETE_MAIN_INTRO_IMAGE(2808, "Cannot delete main intro image"),
    TITLE_CONTAIN_FILTER_WORD(2809, "제목에 금칙어가 포함되어 있습니다."),
    CONTENT_CONTAIN_FILTER_WORD(2810, "본문에 금칙어가 포함되어 있습니다."),
    TITLE_AND_CONTENT_CONTAIN_FILTER_WORD(2811, "제목과 본문에 금칙어가 포함되어 있습니다."),
    FORCE_FOLLOW_CHANNEL_NOT_EXISTS(2812, "강제 팔로워할 대상이 존재하지않습니다."),
    POST_ALREADY_REPORTED(2900, "이미 신고되었습니다."),
    USER_TEAM_JOIN_IMPOSSIBLE(2901, "팀 가입이불가능합니다."),
    USER_TEAM_STATUS_CHANGE_IMPOSSIBLE(2902, "유저팀 가입상태변경이 불가능합니다."),
    PUSH_SEND_FAIL(2903, "푸시발송 실패"),
    USER_TEAM_ALREADY_JOINED_ANOTHER_TEAM(2904, "이미 다른팀에 가입된 유저입니다."),
    ALREADY_APPLIED(2903, "이미 신청되었습니다."),
    PHONE_NUMBER_NOT_CERTIFIED(2904, "전화번호가 인증되지 않았습니다."),
    EVENT_INFO_PROIED_NOT_AGREE(2905, "이벤트 경품 발송 정보제공을 동의해주세요."),
    EVENT_STORE_IMAGE_NOT_ATTACHED(2906, "스토어 이미지를 첨부해주세요."),
    EVENT_CERT_NUMBER_SMS_SEND_FAIL(2907, "인증 문자 발송에 실패하였습니다."),
    EVENT_STOPPED(2908, "이벤트 기간이 아닙니다."),
    EVENT_INPUT_INVALID(2909, "입력 값을 확인하세요."),
    ALREADY_APPLIED_DEVICE(2910, "이미 참여한 휴대폰 입니다."),
    ALREADY_APPLIED_PHONE_NUMBER(2911, "이미 참여한 휴대폰 번호입니다. 참여일시 : %s"),
    PHONE_ALREADY_USED(2912, "다른 계정으로 이벤트 신청이 완료되었습니다. 문상지급은 1인당 1회만 지급됩니다. 문의 faq@gameduck.com"),
    ISSUABLE_COUPON_NOT_FOUND(2913, "발행가능한 쿠폰이 없습니다."),
    CANNOT_CHANGE_ISSUE_ROUND(2914, "회차를 변경 할 수 없습니다."),
    ISSUE_ROUND_IS_NULL(2915, "회차가 비어있습니다."),
    CANNOT_DELETE_ISSUE_ROUND(2916, "회차를 지울 수 없습니다."),
    USER_TEAM_MEMBER_COUNT_OVER_LIMIT(2920, "팀의 허용 멤버수를 초과하여 신청할 수 없습니다."),
    YOUTUBE_CHANNEL_SUBSCRIBE_COUNT_LIMIT_OVER(2921, "구독가능한 채널수({0})를 초과하였습니다."),
    DEVICE_BLOCK(2922, "해당 단말은 운영정책 위반으로 인해 서비스 이용이 제한되었습니다."),
    EMPTY_PARAMETER(3000, "파라미터가 null이거나 빈값, 0입니다."),
    NEED_LOGIN(4000, "로그인이 필요합니다."),
    USER_ID_IS_NULL(4001, "유저ID가 비어있습니다."),
    BADGE_ID_IS_NULL(4002, "뱃지ID가 비어있습니다."),
    USER_EGG_NOT_ENOUGH(2923, "사용할 알이 충분하지 않습니다."),
    USER_ITEM_CANNOT_USE(2924, "유저아이템을 사용할 수 없습니다."),
    USER_ITEM_CANNOT_USE_IN_LIMIT_HOURS(2925, "일정기간안에 같은 유저아이템을 사용할 수 없습니다."),
    USABLE_USER_ITEM_NOT_FOUND(2926, "사용가능한 아이템이 없습니다."),
    ALREADY_ITEM_USED_POST(2927, "이미 아이템 사용된 포스트 입니다."),
    USER_EGG_DAILY_EVENT_CANNOT_APPLY(2928, "일일 알 획득 이벤트에 참여할 수 없습니다."),
    CANNOT_GIVE_EGG_TO_SAME_DEVICE_USED_USER(2929, "같은 단말을 사용한 유저에게 알을 선물 할 수 없습니다."),
    CURRENT_USER_DEVICE_NULL(2930, "현재 유저의 단말기 정보가 없습니다."),
    USER_ITEM_BUY_LIMIT_OVER(2931, "아이템을 구매할 수 있는 수량을 초과하였습니다."),
    BEST_POST_COMMENT_DELETE_FAIL(2932, "제목으로 선정된 댓글은 본인이외에는 삭제 할 수 없습니다."),
    POST_COMMENT_DELETE_FAIL(2933, "댓글 삭제는 포스트의 작성자나 댓글의 작성자만 가능합니다."),
    ACTION_NOT_PERMITTED_TO_MANAGER(2934, "운영자에게는 해당 액션을 하실수 없습니다."),
    USER_ALREADY_FAVORITE_USER(2935, "이미 즐겨찾기한 유저입니다."),
    USER_ALREADY_FOLLOW(2936, "이미 팔로우한 유저입니다."),
    ALREADY_MESSAGE_ROOM_PARTICIPANT(2937, "{0} 님은 이미 채팅방에 참여한 유저입니다."),
    MESSAGE_ROOM_CANNOT_INVITE_CAPACITY_EXCEED(2938, "방의 인원수를 초과하여 더이상 초대할 수 없습니다."),
    TEAM_CHAT_ROOM_INVITE_IMPOSSIBLE(2939, "팀 채팅방은 초대기능을 사용할 수 없습니다"),
    MESSAGE_ROOM_CANNOT_CREATE_CAPACITY_EXCEED(2940, "방의 최대 인원수를 초과하여 방을 생성할 수 없습니다."),
    SUB_MANAGER_NOT_APPLY_REASON_MANAGER(2941, "팀장은 부팀장이 될 수 없습니다."),
    SUB_MANAGER_CHANGE(2942, "{0}님을 새로운 부팀장으로 임명 하시겠습니까?"),
    NOT_TEAM_MANAGER_AND_SUB_MANAGER(2943, "팀장과 부팀장만 사용 가능한 메뉴 입니다."),
    SELECT_MEMBER_SUB_MANAGER(2946, "해당 팀원은 이미 부팀장 입니다."),
    INVITE_COMPLETE_WITHOUT_BLOCKED_USER(2947, "이 단톡방에 참여하고 싶어하지 않은 친구는 초대에서 제외되었습니다."),
    INVITE_FAIL_ALL_BLOCKED_USER(2948, "초대한 유저가 단톡방 참여를 거부했습니다."),
    SOCIAL_LOGIN_FAIL(2949, "소셜로그인이 실패했습니다."),
    SOCIAL_LOGIN_STATE_NOT_MATCHED(2950, "소셜로그인시 STATE 값이 맞지 않습니다."),
    LIVE_END(2951, "종료된 방송입니다."),
    LIVE_IMPOSSIBLE(2952, "해당 채널은 라이브 방송을 할 수 없습니다."),
    FEATHER_NOT_ENOUGH(2953, "깃털이 모자 랍니다."),
    LIVE_END_AFTER_POST_GET(2954, "종료된 방송입니다. 포스트로 방문 하시겠습니까?");

    private final int code;
    private final String messsage;
}
